### ISSUE TITLE
Wrong compatibility declaration

### ISSUE THREAD

**Issue by CyrilleB79** [josephsl/addonUpdater#22]
### Issue
Add-on Updater claims to be compatible with NVDA 2023.1 onwards.

But starting with NVDA 2023.1, I get the following error in the log:

```
ERROR - globalPluginHandler.listPlugins (09:51:32.045) - MainThread (1496):
Error importing global plugin addonUpdater
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\addonUpdater\globalPlugins\addonUpdater\__init__.py", line 21, in <module>
    from . import addonHandlerEx
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\addonUpdater\globalPlugins\addonUpdater\addonHandlerEx.py", line 19, in <module>
    from . import addonUpdateProc
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\addonUpdater\globalPlugins\addonUpdater\addonUpdateProc.py", line 24, in <module>
    from NVDAState import WritePaths
ImportError: cannot import name 'WritePaths' from 'NVDAState' (C:\Users\CB232690\AppData\Local\Temp\nseEDD4.tmp\app\library.zip\NVDAState.pyc)
```

 ### Solution
* Either reduce compatibility range
* Or update the code to be compatible with older versions and re-test it.

**Comment by josephsl** [comment]
Hi,

I think it would make sense to keep the issue open as is or close it as the ability to notify people about add-on updates was just merged into NVDA Core master branch and is scheduled for 2024.3. CC @XLTechie

**Comment by CyrilleB79** [comment]
Hi

I would keep it open as explained in https://github.com/josephsl/addonUpdater/issues/8#issuecomment-2162304335 for #8.
In one word, keep it open even if the add-on is discontinued so that existing issues in the current add-on's code remain documented in case someone want to reuse this code.

**Comment by josephsl** [comment]
Hi,

I'm leaning towards closing this as Add-on Updater is under deep maintenance by Luke (on life support at the moment as I have officially discontinued the add-on last year).

Thanks.

**Comment by XLTechie** [comment]
Actually, I will fix this one. It is within the scope of maintenance and critical bugfixes.

**Comment by XLTechie** [comment]
@CyrilleB79
This is fixed in:

* [Stable version 24.2.4](https://github.com/josephsl/addonUpdater/releases/download/v24.2.4/addonUpdater-24.2.4.nvda-addon)
* [Beta version 24.2.104](https://github.com/josephsl/addonUpdater/releases/download/v24.2.104-beta/addonUpdater-24.2.104.nvda-addon)
* [Dev version 24.2.504﻿](https://github.com/josephsl/addonUpdater/releases/download/v24.2.504-dev/addonUpdater-24.2.504.nvda-addon)
